/*
 * This file is generated by jOOQ.
 */
package com.siyuo2o.glass.db.album.tables.daos;


import com.siyuo2o.glass.db.album.enums.SysPermissionResourceType;
import com.siyuo2o.glass.db.album.tables.SysPermission;
import com.siyuo2o.glass.db.album.tables.records.SysPermissionRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysPermissionDao extends DAOImpl<SysPermissionRecord, com.siyuo2o.glass.db.album.tables.pojos.SysPermission, Integer> {

    /**
     * Create a new SysPermissionDao without any configuration
     */
    public SysPermissionDao() {
        super(SysPermission.SYS_PERMISSION, com.siyuo2o.glass.db.album.tables.pojos.SysPermission.class);
    }

    /**
     * Create a new SysPermissionDao with an attached configuration
     */
    public SysPermissionDao(Configuration configuration) {
        super(SysPermission.SYS_PERMISSION, com.siyuo2o.glass.db.album.tables.pojos.SysPermission.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.siyuo2o.glass.db.album.tables.pojos.SysPermission object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.siyuo2o.glass.db.album.tables.pojos.SysPermission> fetchById(Integer... values) {
        return fetch(SysPermission.SYS_PERMISSION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.siyuo2o.glass.db.album.tables.pojos.SysPermission fetchOneById(Integer value) {
        return fetchOne(SysPermission.SYS_PERMISSION.ID, value);
    }

    /**
     * Fetch records that have <code>available IN (values)</code>
     */
    public List<com.siyuo2o.glass.db.album.tables.pojos.SysPermission> fetchByAvailable(Boolean... values) {
        return fetch(SysPermission.SYS_PERMISSION.AVAILABLE, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.siyuo2o.glass.db.album.tables.pojos.SysPermission> fetchByName(String... values) {
        return fetch(SysPermission.SYS_PERMISSION.NAME, values);
    }

    /**
     * Fetch records that have <code>parent_id IN (values)</code>
     */
    public List<com.siyuo2o.glass.db.album.tables.pojos.SysPermission> fetchByParentId(Long... values) {
        return fetch(SysPermission.SYS_PERMISSION.PARENT_ID, values);
    }

    /**
     * Fetch records that have <code>parent_ids IN (values)</code>
     */
    public List<com.siyuo2o.glass.db.album.tables.pojos.SysPermission> fetchByParentIds(String... values) {
        return fetch(SysPermission.SYS_PERMISSION.PARENT_IDS, values);
    }

    /**
     * Fetch records that have <code>permission IN (values)</code>
     */
    public List<com.siyuo2o.glass.db.album.tables.pojos.SysPermission> fetchByPermission(String... values) {
        return fetch(SysPermission.SYS_PERMISSION.PERMISSION, values);
    }

    /**
     * Fetch records that have <code>resource_type IN (values)</code>
     */
    public List<com.siyuo2o.glass.db.album.tables.pojos.SysPermission> fetchByResourceType(SysPermissionResourceType... values) {
        return fetch(SysPermission.SYS_PERMISSION.RESOURCE_TYPE, values);
    }

    /**
     * Fetch records that have <code>url IN (values)</code>
     */
    public List<com.siyuo2o.glass.db.album.tables.pojos.SysPermission> fetchByUrl(String... values) {
        return fetch(SysPermission.SYS_PERMISSION.URL, values);
    }
}
