/*
 * This file is generated by jOOQ.
 */
package com.siyuo2o.glass.db.album.tables.daos;


import com.siyuo2o.glass.db.album.tables.SysRole;
import com.siyuo2o.glass.db.album.tables.records.SysRoleRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRoleDao extends DAOImpl<SysRoleRecord, com.siyuo2o.glass.db.album.tables.pojos.SysRole, Integer> {

    /**
     * Create a new SysRoleDao without any configuration
     */
    public SysRoleDao() {
        super(SysRole.SYS_ROLE, com.siyuo2o.glass.db.album.tables.pojos.SysRole.class);
    }

    /**
     * Create a new SysRoleDao with an attached configuration
     */
    public SysRoleDao(Configuration configuration) {
        super(SysRole.SYS_ROLE, com.siyuo2o.glass.db.album.tables.pojos.SysRole.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.siyuo2o.glass.db.album.tables.pojos.SysRole object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.siyuo2o.glass.db.album.tables.pojos.SysRole> fetchById(Integer... values) {
        return fetch(SysRole.SYS_ROLE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.siyuo2o.glass.db.album.tables.pojos.SysRole fetchOneById(Integer value) {
        return fetchOne(SysRole.SYS_ROLE.ID, value);
    }

    /**
     * Fetch records that have <code>available IN (values)</code>
     */
    public List<com.siyuo2o.glass.db.album.tables.pojos.SysRole> fetchByAvailable(Boolean... values) {
        return fetch(SysRole.SYS_ROLE.AVAILABLE, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.siyuo2o.glass.db.album.tables.pojos.SysRole> fetchByDescription(String... values) {
        return fetch(SysRole.SYS_ROLE.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>role IN (values)</code>
     */
    public List<com.siyuo2o.glass.db.album.tables.pojos.SysRole> fetchByRole(String... values) {
        return fetch(SysRole.SYS_ROLE.ROLE, values);
    }
}
