/*
 * This file is generated by jOOQ.
 */
package com.siyuo2o.glass.db.album.tables.daos;


import com.siyuo2o.glass.db.album.tables.User;
import com.siyuo2o.glass.db.album.tables.records.UserRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDao extends DAOImpl<UserRecord, com.siyuo2o.glass.db.album.tables.pojos.User, Integer> {

    /**
     * Create a new UserDao without any configuration
     */
    public UserDao() {
        super(User.USER, com.siyuo2o.glass.db.album.tables.pojos.User.class);
    }

    /**
     * Create a new UserDao with an attached configuration
     */
    public UserDao(Configuration configuration) {
        super(User.USER, com.siyuo2o.glass.db.album.tables.pojos.User.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.siyuo2o.glass.db.album.tables.pojos.User object) {
        return object.getUid();
    }

    /**
     * Fetch records that have <code>uid IN (values)</code>
     */
    public List<com.siyuo2o.glass.db.album.tables.pojos.User> fetchByUid(Integer... values) {
        return fetch(User.USER.UID, values);
    }

    /**
     * Fetch a unique record that has <code>uid = value</code>
     */
    public com.siyuo2o.glass.db.album.tables.pojos.User fetchOneByUid(Integer value) {
        return fetchOne(User.USER.UID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.siyuo2o.glass.db.album.tables.pojos.User> fetchByName(String... values) {
        return fetch(User.USER.NAME, values);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<com.siyuo2o.glass.db.album.tables.pojos.User> fetchByPassword(String... values) {
        return fetch(User.USER.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>salt IN (values)</code>
     */
    public List<com.siyuo2o.glass.db.album.tables.pojos.User> fetchBySalt(String... values) {
        return fetch(User.USER.SALT, values);
    }

    /**
     * Fetch records that have <code>state IN (values)</code>
     */
    public List<com.siyuo2o.glass.db.album.tables.pojos.User> fetchByState(Byte... values) {
        return fetch(User.USER.STATE, values);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<com.siyuo2o.glass.db.album.tables.pojos.User> fetchByUsername(String... values) {
        return fetch(User.USER.USERNAME, values);
    }
}
