/*
 * This file is generated by jOOQ.
 */
package com.siyuo2o.glass.db.album.tables.daos;


import com.siyuo2o.glass.db.album.tables.UserInfo;
import com.siyuo2o.glass.db.album.tables.records.UserInfoRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserInfoDao extends DAOImpl<UserInfoRecord, com.siyuo2o.glass.db.album.tables.pojos.UserInfo, Integer> {

    /**
     * Create a new UserInfoDao without any configuration
     */
    public UserInfoDao() {
        super(UserInfo.USER_INFO, com.siyuo2o.glass.db.album.tables.pojos.UserInfo.class);
    }

    /**
     * Create a new UserInfoDao with an attached configuration
     */
    public UserInfoDao(Configuration configuration) {
        super(UserInfo.USER_INFO, com.siyuo2o.glass.db.album.tables.pojos.UserInfo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.siyuo2o.glass.db.album.tables.pojos.UserInfo object) {
        return object.getUid();
    }

    /**
     * Fetch records that have <code>uid IN (values)</code>
     */
    public List<com.siyuo2o.glass.db.album.tables.pojos.UserInfo> fetchByUid(Integer... values) {
        return fetch(UserInfo.USER_INFO.UID, values);
    }

    /**
     * Fetch a unique record that has <code>uid = value</code>
     */
    public com.siyuo2o.glass.db.album.tables.pojos.UserInfo fetchOneByUid(Integer value) {
        return fetchOne(UserInfo.USER_INFO.UID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.siyuo2o.glass.db.album.tables.pojos.UserInfo> fetchByName(String... values) {
        return fetch(UserInfo.USER_INFO.NAME, values);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<com.siyuo2o.glass.db.album.tables.pojos.UserInfo> fetchByPassword(String... values) {
        return fetch(UserInfo.USER_INFO.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>state IN (values)</code>
     */
    public List<com.siyuo2o.glass.db.album.tables.pojos.UserInfo> fetchByState(Byte... values) {
        return fetch(UserInfo.USER_INFO.STATE, values);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<com.siyuo2o.glass.db.album.tables.pojos.UserInfo> fetchByUsername(String... values) {
        return fetch(UserInfo.USER_INFO.USERNAME, values);
    }
}
