/*
 * This file is generated by jOOQ.
 */
package com.siyuo2o.glass.db.album.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRolePermission implements Serializable {

    private static final long serialVersionUID = -1150217412;

    private Integer permissionId;
    private Integer roleId;

    public SysRolePermission() {}

    public SysRolePermission(SysRolePermission value) {
        this.permissionId = value.permissionId;
        this.roleId = value.roleId;
    }

    public SysRolePermission(
        Integer permissionId,
        Integer roleId
    ) {
        this.permissionId = permissionId;
        this.roleId = roleId;
    }

    public Integer getPermissionId() {
        return this.permissionId;
    }

    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysRolePermission (");

        sb.append(permissionId);
        sb.append(", ").append(roleId);

        sb.append(")");
        return sb.toString();
    }
}
