/*
 * This file is generated by jOOQ.
 */
package com.siyuo2o.glass.db.album.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserRole implements Serializable {

    private static final long serialVersionUID = -933588726;

    private Integer uid;
    private Integer roleId;

    public SysUserRole() {}

    public SysUserRole(SysUserRole value) {
        this.uid = value.uid;
        this.roleId = value.roleId;
    }

    public SysUserRole(
        Integer uid,
        Integer roleId
    ) {
        this.uid = uid;
        this.roleId = roleId;
    }

    public Integer getUid() {
        return this.uid;
    }

    public void setUid(Integer uid) {
        this.uid = uid;
    }

    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysUserRole (");

        sb.append(uid);
        sb.append(", ").append(roleId);

        sb.append(")");
        return sb.toString();
    }
}
