/*
 * This file is generated by jOOQ.
 */
package com.siyuo2o.glass.db.album.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 62393662;

    private Integer uid;
    private String  name;
    private String  password;
    private String  salt;
    private Byte    state;
    private String  username;

    public User() {}

    public User(User value) {
        this.uid = value.uid;
        this.name = value.name;
        this.password = value.password;
        this.salt = value.salt;
        this.state = value.state;
        this.username = value.username;
    }

    public User(
        Integer uid,
        String  name,
        String  password,
        String  salt,
        Byte    state,
        String  username
    ) {
        this.uid = uid;
        this.name = name;
        this.password = password;
        this.salt = salt;
        this.state = state;
        this.username = username;
    }

    public Integer getUid() {
        return this.uid;
    }

    public void setUid(Integer uid) {
        this.uid = uid;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getSalt() {
        return this.salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }

    public Byte getState() {
        return this.state;
    }

    public void setState(Byte state) {
        this.state = state;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(uid);
        sb.append(", ").append(name);
        sb.append(", ").append(password);
        sb.append(", ").append(salt);
        sb.append(", ").append(state);
        sb.append(", ").append(username);

        sb.append(")");
        return sb.toString();
    }
}
