/*
 * This file is generated by jOOQ.
 */
package com.siyuo2o.glass.db.album;


import com.siyuo2o.glass.db.album.tables.HibernateSequence;
import com.siyuo2o.glass.db.album.tables.Image;
import com.siyuo2o.glass.db.album.tables.SysPermission;
import com.siyuo2o.glass.db.album.tables.SysRole;
import com.siyuo2o.glass.db.album.tables.SysRolePermission;
import com.siyuo2o.glass.db.album.tables.SysUserRole;
import com.siyuo2o.glass.db.album.tables.User;
import com.siyuo2o.glass.db.album.tables.UserInfo;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Album extends SchemaImpl {

    private static final long serialVersionUID = -129064711;

    /**
     * The reference instance of <code>album</code>
     */
    public static final Album ALBUM = new Album();

    /**
     * The table <code>album.album</code>.
     */
    public final com.siyuo2o.glass.db.album.tables.Album ALBUM_ = com.siyuo2o.glass.db.album.tables.Album.ALBUM_;

    /**
     * The table <code>album.hibernate_sequence</code>.
     */
    public final HibernateSequence HIBERNATE_SEQUENCE = com.siyuo2o.glass.db.album.tables.HibernateSequence.HIBERNATE_SEQUENCE;

    /**
     * The table <code>album.image</code>.
     */
    public final Image IMAGE = com.siyuo2o.glass.db.album.tables.Image.IMAGE;

    /**
     * The table <code>album.sys_permission</code>.
     */
    public final SysPermission SYS_PERMISSION = com.siyuo2o.glass.db.album.tables.SysPermission.SYS_PERMISSION;

    /**
     * The table <code>album.sys_role</code>.
     */
    public final SysRole SYS_ROLE = com.siyuo2o.glass.db.album.tables.SysRole.SYS_ROLE;

    /**
     * The table <code>album.sys_role_permission</code>.
     */
    public final SysRolePermission SYS_ROLE_PERMISSION = com.siyuo2o.glass.db.album.tables.SysRolePermission.SYS_ROLE_PERMISSION;

    /**
     * The table <code>album.sys_user_role</code>.
     */
    public final SysUserRole SYS_USER_ROLE = com.siyuo2o.glass.db.album.tables.SysUserRole.SYS_USER_ROLE;

    /**
     * The table <code>album.user</code>.
     */
    public final User USER = com.siyuo2o.glass.db.album.tables.User.USER;

    /**
     * The table <code>album.user_info</code>.
     */
    public final UserInfo USER_INFO = com.siyuo2o.glass.db.album.tables.UserInfo.USER_INFO;

    /**
     * No further instances allowed
     */
    private Album() {
        super("album", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            com.siyuo2o.glass.db.album.tables.Album.ALBUM_,
            HibernateSequence.HIBERNATE_SEQUENCE,
            Image.IMAGE,
            SysPermission.SYS_PERMISSION,
            SysRole.SYS_ROLE,
            SysRolePermission.SYS_ROLE_PERMISSION,
            SysUserRole.SYS_USER_ROLE,
            User.USER,
            UserInfo.USER_INFO);
    }
}
