/*
 * This file is generated by jOOQ.
 */
package com.siyuo2o.glass.db.album;


import com.siyuo2o.glass.db.album.tables.Album;
import com.siyuo2o.glass.db.album.tables.Image;
import com.siyuo2o.glass.db.album.tables.SysPermission;
import com.siyuo2o.glass.db.album.tables.SysRole;
import com.siyuo2o.glass.db.album.tables.SysRolePermission;
import com.siyuo2o.glass.db.album.tables.SysUserRole;
import com.siyuo2o.glass.db.album.tables.User;
import com.siyuo2o.glass.db.album.tables.UserInfo;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>album</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ALBUM_PRIMARY = Indexes0.ALBUM_PRIMARY;
    public static final Index IMAGE_PRIMARY = Indexes0.IMAGE_PRIMARY;
    public static final Index SYS_PERMISSION_PRIMARY = Indexes0.SYS_PERMISSION_PRIMARY;
    public static final Index SYS_ROLE_PRIMARY = Indexes0.SYS_ROLE_PRIMARY;
    public static final Index SYS_ROLE_PERMISSION_FK9Q28EWRHNTQEIPL1T04KH1BE7 = Indexes0.SYS_ROLE_PERMISSION_FK9Q28EWRHNTQEIPL1T04KH1BE7;
    public static final Index SYS_ROLE_PERMISSION_FKOMXRS8A388BKNVHJOKH440WAQ = Indexes0.SYS_ROLE_PERMISSION_FKOMXRS8A388BKNVHJOKH440WAQ;
    public static final Index SYS_USER_ROLE_FKGKMYSLKRFEYN9UKMOLVEK8B8F = Indexes0.SYS_USER_ROLE_FKGKMYSLKRFEYN9UKMOLVEK8B8F;
    public static final Index SYS_USER_ROLE_FKHH52N8VD4NY9FF4X9FB8V65QX = Indexes0.SYS_USER_ROLE_FKHH52N8VD4NY9FF4X9FB8V65QX;
    public static final Index USER_PRIMARY = Indexes0.USER_PRIMARY;
    public static final Index USER_INFO_PRIMARY = Indexes0.USER_INFO_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ALBUM_PRIMARY = Internal.createIndex("PRIMARY", Album.ALBUM_, new OrderField[] { Album.ALBUM_.ID }, true);
        public static Index IMAGE_PRIMARY = Internal.createIndex("PRIMARY", Image.IMAGE, new OrderField[] { Image.IMAGE.ID }, true);
        public static Index SYS_PERMISSION_PRIMARY = Internal.createIndex("PRIMARY", SysPermission.SYS_PERMISSION, new OrderField[] { SysPermission.SYS_PERMISSION.ID }, true);
        public static Index SYS_ROLE_PRIMARY = Internal.createIndex("PRIMARY", SysRole.SYS_ROLE, new OrderField[] { SysRole.SYS_ROLE.ID }, true);
        public static Index SYS_ROLE_PERMISSION_FK9Q28EWRHNTQEIPL1T04KH1BE7 = Internal.createIndex("FK9q28ewrhntqeipl1t04kh1be7", SysRolePermission.SYS_ROLE_PERMISSION, new OrderField[] { SysRolePermission.SYS_ROLE_PERMISSION.ROLE_ID }, false);
        public static Index SYS_ROLE_PERMISSION_FKOMXRS8A388BKNVHJOKH440WAQ = Internal.createIndex("FKomxrs8a388bknvhjokh440waq", SysRolePermission.SYS_ROLE_PERMISSION, new OrderField[] { SysRolePermission.SYS_ROLE_PERMISSION.PERMISSION_ID }, false);
        public static Index SYS_USER_ROLE_FKGKMYSLKRFEYN9UKMOLVEK8B8F = Internal.createIndex("FKgkmyslkrfeyn9ukmolvek8b8f", SysUserRole.SYS_USER_ROLE, new OrderField[] { SysUserRole.SYS_USER_ROLE.UID }, false);
        public static Index SYS_USER_ROLE_FKHH52N8VD4NY9FF4X9FB8V65QX = Internal.createIndex("FKhh52n8vd4ny9ff4x9fb8v65qx", SysUserRole.SYS_USER_ROLE, new OrderField[] { SysUserRole.SYS_USER_ROLE.ROLE_ID }, false);
        public static Index USER_PRIMARY = Internal.createIndex("PRIMARY", User.USER, new OrderField[] { User.USER.UID }, true);
        public static Index USER_INFO_PRIMARY = Internal.createIndex("PRIMARY", UserInfo.USER_INFO, new OrderField[] { UserInfo.USER_INFO.UID }, true);
    }
}
