/*
 * This file is generated by jOOQ.
 */
package com.siyuo2o.glass.db.album;


import com.siyuo2o.glass.db.album.tables.Album;
import com.siyuo2o.glass.db.album.tables.Image;
import com.siyuo2o.glass.db.album.tables.SysPermission;
import com.siyuo2o.glass.db.album.tables.SysRole;
import com.siyuo2o.glass.db.album.tables.SysRolePermission;
import com.siyuo2o.glass.db.album.tables.SysUserRole;
import com.siyuo2o.glass.db.album.tables.User;
import com.siyuo2o.glass.db.album.tables.UserInfo;
import com.siyuo2o.glass.db.album.tables.records.AlbumRecord;
import com.siyuo2o.glass.db.album.tables.records.ImageRecord;
import com.siyuo2o.glass.db.album.tables.records.SysPermissionRecord;
import com.siyuo2o.glass.db.album.tables.records.SysRolePermissionRecord;
import com.siyuo2o.glass.db.album.tables.records.SysRoleRecord;
import com.siyuo2o.glass.db.album.tables.records.SysUserRoleRecord;
import com.siyuo2o.glass.db.album.tables.records.UserInfoRecord;
import com.siyuo2o.glass.db.album.tables.records.UserRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>album</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AlbumRecord, Integer> IDENTITY_ALBUM_ = Identities0.IDENTITY_ALBUM_;
    public static final Identity<ImageRecord, Integer> IDENTITY_IMAGE = Identities0.IDENTITY_IMAGE;
    public static final Identity<UserInfoRecord, Integer> IDENTITY_USER_INFO = Identities0.IDENTITY_USER_INFO;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AlbumRecord> KEY_ALBUM_PRIMARY = UniqueKeys0.KEY_ALBUM_PRIMARY;
    public static final UniqueKey<ImageRecord> KEY_IMAGE_PRIMARY = UniqueKeys0.KEY_IMAGE_PRIMARY;
    public static final UniqueKey<SysPermissionRecord> KEY_SYS_PERMISSION_PRIMARY = UniqueKeys0.KEY_SYS_PERMISSION_PRIMARY;
    public static final UniqueKey<SysRoleRecord> KEY_SYS_ROLE_PRIMARY = UniqueKeys0.KEY_SYS_ROLE_PRIMARY;
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;
    public static final UniqueKey<UserInfoRecord> KEY_USER_INFO_PRIMARY = UniqueKeys0.KEY_USER_INFO_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<SysRolePermissionRecord, SysPermissionRecord> FKOMXRS8A388BKNVHJOKH440WAQ = ForeignKeys0.FKOMXRS8A388BKNVHJOKH440WAQ;
    public static final ForeignKey<SysRolePermissionRecord, SysRoleRecord> FK9Q28EWRHNTQEIPL1T04KH1BE7 = ForeignKeys0.FK9Q28EWRHNTQEIPL1T04KH1BE7;
    public static final ForeignKey<SysUserRoleRecord, UserRecord> FK265KTP12FYG5P1I1H4FS5XI4W = ForeignKeys0.FK265KTP12FYG5P1I1H4FS5XI4W;
    public static final ForeignKey<SysUserRoleRecord, UserInfoRecord> FKGKMYSLKRFEYN9UKMOLVEK8B8F = ForeignKeys0.FKGKMYSLKRFEYN9UKMOLVEK8B8F;
    public static final ForeignKey<SysUserRoleRecord, SysRoleRecord> FKHH52N8VD4NY9FF4X9FB8V65QX = ForeignKeys0.FKHH52N8VD4NY9FF4X9FB8V65QX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<AlbumRecord, Integer> IDENTITY_ALBUM_ = Internal.createIdentity(Album.ALBUM_, Album.ALBUM_.ID);
        public static Identity<ImageRecord, Integer> IDENTITY_IMAGE = Internal.createIdentity(Image.IMAGE, Image.IMAGE.ID);
        public static Identity<UserInfoRecord, Integer> IDENTITY_USER_INFO = Internal.createIdentity(UserInfo.USER_INFO, UserInfo.USER_INFO.UID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AlbumRecord> KEY_ALBUM_PRIMARY = Internal.createUniqueKey(Album.ALBUM_, "KEY_album_PRIMARY", Album.ALBUM_.ID);
        public static final UniqueKey<ImageRecord> KEY_IMAGE_PRIMARY = Internal.createUniqueKey(Image.IMAGE, "KEY_image_PRIMARY", Image.IMAGE.ID);
        public static final UniqueKey<SysPermissionRecord> KEY_SYS_PERMISSION_PRIMARY = Internal.createUniqueKey(SysPermission.SYS_PERMISSION, "KEY_sys_permission_PRIMARY", SysPermission.SYS_PERMISSION.ID);
        public static final UniqueKey<SysRoleRecord> KEY_SYS_ROLE_PRIMARY = Internal.createUniqueKey(SysRole.SYS_ROLE, "KEY_sys_role_PRIMARY", SysRole.SYS_ROLE.ID);
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER, "KEY_user_PRIMARY", User.USER.UID);
        public static final UniqueKey<UserInfoRecord> KEY_USER_INFO_PRIMARY = Internal.createUniqueKey(UserInfo.USER_INFO, "KEY_user_info_PRIMARY", UserInfo.USER_INFO.UID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<SysRolePermissionRecord, SysPermissionRecord> FKOMXRS8A388BKNVHJOKH440WAQ = Internal.createForeignKey(com.siyuo2o.glass.db.album.Keys.KEY_SYS_PERMISSION_PRIMARY, SysRolePermission.SYS_ROLE_PERMISSION, "FKomxrs8a388bknvhjokh440waq", SysRolePermission.SYS_ROLE_PERMISSION.PERMISSION_ID);
        public static final ForeignKey<SysRolePermissionRecord, SysRoleRecord> FK9Q28EWRHNTQEIPL1T04KH1BE7 = Internal.createForeignKey(com.siyuo2o.glass.db.album.Keys.KEY_SYS_ROLE_PRIMARY, SysRolePermission.SYS_ROLE_PERMISSION, "FK9q28ewrhntqeipl1t04kh1be7", SysRolePermission.SYS_ROLE_PERMISSION.ROLE_ID);
        public static final ForeignKey<SysUserRoleRecord, UserRecord> FK265KTP12FYG5P1I1H4FS5XI4W = Internal.createForeignKey(com.siyuo2o.glass.db.album.Keys.KEY_USER_PRIMARY, SysUserRole.SYS_USER_ROLE, "FK265ktp12fyg5p1i1h4fs5xi4w", SysUserRole.SYS_USER_ROLE.UID);
        public static final ForeignKey<SysUserRoleRecord, UserInfoRecord> FKGKMYSLKRFEYN9UKMOLVEK8B8F = Internal.createForeignKey(com.siyuo2o.glass.db.album.Keys.KEY_USER_INFO_PRIMARY, SysUserRole.SYS_USER_ROLE, "FKgkmyslkrfeyn9ukmolvek8b8f", SysUserRole.SYS_USER_ROLE.UID);
        public static final ForeignKey<SysUserRoleRecord, SysRoleRecord> FKHH52N8VD4NY9FF4X9FB8V65QX = Internal.createForeignKey(com.siyuo2o.glass.db.album.Keys.KEY_SYS_ROLE_PRIMARY, SysUserRole.SYS_USER_ROLE, "FKhh52n8vd4ny9ff4x9fb8v65qx", SysUserRole.SYS_USER_ROLE.ROLE_ID);
    }
}
