/*
 * This file is generated by jOOQ.
 */
package com.siyuo2o.glass.db.album;


import com.siyuo2o.glass.db.album.tables.Album;
import com.siyuo2o.glass.db.album.tables.HibernateSequence;
import com.siyuo2o.glass.db.album.tables.Image;
import com.siyuo2o.glass.db.album.tables.SysPermission;
import com.siyuo2o.glass.db.album.tables.SysRole;
import com.siyuo2o.glass.db.album.tables.SysRolePermission;
import com.siyuo2o.glass.db.album.tables.SysUserRole;
import com.siyuo2o.glass.db.album.tables.User;
import com.siyuo2o.glass.db.album.tables.UserInfo;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in album
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>album.album</code>.
     */
    public static final Album ALBUM_ = com.siyuo2o.glass.db.album.tables.Album.ALBUM_;

    /**
     * The table <code>album.hibernate_sequence</code>.
     */
    public static final HibernateSequence HIBERNATE_SEQUENCE = com.siyuo2o.glass.db.album.tables.HibernateSequence.HIBERNATE_SEQUENCE;

    /**
     * The table <code>album.image</code>.
     */
    public static final Image IMAGE = com.siyuo2o.glass.db.album.tables.Image.IMAGE;

    /**
     * The table <code>album.sys_permission</code>.
     */
    public static final SysPermission SYS_PERMISSION = com.siyuo2o.glass.db.album.tables.SysPermission.SYS_PERMISSION;

    /**
     * The table <code>album.sys_role</code>.
     */
    public static final SysRole SYS_ROLE = com.siyuo2o.glass.db.album.tables.SysRole.SYS_ROLE;

    /**
     * The table <code>album.sys_role_permission</code>.
     */
    public static final SysRolePermission SYS_ROLE_PERMISSION = com.siyuo2o.glass.db.album.tables.SysRolePermission.SYS_ROLE_PERMISSION;

    /**
     * The table <code>album.sys_user_role</code>.
     */
    public static final SysUserRole SYS_USER_ROLE = com.siyuo2o.glass.db.album.tables.SysUserRole.SYS_USER_ROLE;

    /**
     * The table <code>album.user</code>.
     */
    public static final User USER = com.siyuo2o.glass.db.album.tables.User.USER;

    /**
     * The table <code>album.user_info</code>.
     */
    public static final UserInfo USER_INFO = com.siyuo2o.glass.db.album.tables.UserInfo.USER_INFO;
}
